//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorNotaDeDebito {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class BusinessConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static BusinessConfig defaultInstance = ((BusinessConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BusinessConfig())));
        
        public static BusinessConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA {
            get {
                return ((string)(this["EMPRESA"]));
            }
            set {
                this["EMPRESA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA_CNPJ {
            get {
                return ((string)(this["EMPRESA_CNPJ"]));
            }
            set {
                this["EMPRESA_CNPJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA_END {
            get {
                return ((string)(this["EMPRESA_END"]));
            }
            set {
                this["EMPRESA_END"] = value;
            }
        }
    }
}
