//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeradorNotaDeDebito.Configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    internal sealed partial class BusinessConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static BusinessConfig defaultInstance = ((BusinessConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BusinessConfig())));
        
        public static BusinessConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA {
            get {
                return ((string)(this["EMPRESA"]));
            }
            set {
                this["EMPRESA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA_CNPJ {
            get {
                return ((string)(this["EMPRESA_CNPJ"]));
            }
            set {
                this["EMPRESA_CNPJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA_END {
            get {
                return ((string)(this["EMPRESA_END"]));
            }
            set {
                this["EMPRESA_END"] = value;
            }
        }
    }
}
